site_name: "GEROcuidado"

repo_name: "2023-2-GEROcuidado-Doc"
repo_url: "https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.pat
    - navigation.sections
    - navigation.expand
  palette:
    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono

  language: "pt"
  logo: "assets/gero.png"
  favicon: "assets/gero.png"

  palette:
    primary: "#fff"
    accent: "#0B4D9B"


extra_css:
  - stylesheets/styles.css

nav:
  - Home: index.md
  - Planejamento:
    - Quadro de disponibilidade: planejamento/quadro_de_disponibilidade.md
    - Quadro de conhecimento: planejamento/quadro_conhecimento.md
    - Plano de contribuição: planejamento/plano_de_contribuicao.md  
    - Plano de comunicação: planejamento/plano_de_comunicacao.md
    - Plano de custos: planejamento/plano_de_custos.md
    - Plano de gerenciamento de risco: planejamento/gerenciamento_de_riscos.md
    - Padrões da comunidade: planejamento/padroes_da_comunidade.md
    - Metodologias: planejamento/metodologia.md
  - Treinamentos:
    - Treinamento de Linux: treinamentos/treinamento_linux.md
    - Treinamento de Git: treinamentos/treinamento_git.md
    - Treinamento de Metodologias Ágeis: treinamentos/treinamento_metodologias_ageis.md
    - Treinamento de SQL: treinamentos/treinamento_SQL.md
  - Reuniões:
    - Semana 1:
      - Reunião EPS 04/09: reunioes/Semana_1/reuniao_EPS_04_09.md
      - Reunião Geral 05/09: reunioes/Semana_1/reuniao_Geral_05_09.md
      - Reunião PO 06/09: reunioes/Semana_1/reuniao_PO_06_09.md
    - Semana 2:
      - Reunião Geral 12/09: reunioes/Semana_2/reuniao_Geral_12_09.md
      - Reunião Lean Inception Dia 1 17/09: reunioes/Semana_2/reuniao_Lean_Inception_Dia1_17_09.md
      - Reunião PO 13/09: reunioes/Semana_2/reuniao_PO_13_09.md
    - Semana 3:
      - Reunião Geral 19/09: reunioes/Semana_3/reuniao_Geral_19_09.md
      - Reunião PO 20/09: reunioes/Semana_3/reuniao_PO_20_09.md
      - Reunião Treinamento e Lean Inception Dia 2 23/09: reunioes/Semana_3/reuniao_Treinamento_e_Lean_Inception_Dia2_23_09.md
    - Semana 4:
      - Reunião Geral 26/09: reunioes/Semana_4/reuniao_Geral_26_09.md
      - Reunião PO 27/09: reunioes/Semana_4/reuniao_PO_27_09.md
    - Semana 5:
      - Reunião Geral 03/10: reunioes/Semana_5/reuniao_Geral_03_10.md

plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
