site_name: "GEROcuidado"

repo_name: "2023-2-GEROcuidado-Doc"
repo_url: "https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.pat
    - navigation.sections
    - navigation.expand
  palette:
    # Palette toggle for automatic mode
    #- media: "(prefers-color-scheme)"
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono

  language: "pt"
  logo: "assets/gero.png"
  favicon: "assets/gero.png"

  palette:
    primary: "#fff"
    accent: "#0B4D9B"


extra_css:
  - stylesheets/styles.css

nav:
  - Home: index.md
  - Planejamento:
    - Plano de contribuição: planejamento/plano_de_contribuicao.md  
    - Plano de comunicação: planejamento/plano_de_comunicacao.md
    - Quadro de disponibilidade: planejamento/quadro_de_disponibilidade.md
    - Metodologias: planejamento/metodologia.md
    - Plano de gerenciamento de risco: planejamento/gerenciamento_de_riscos.md
    


plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets